// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Login_DbContext.Models;
using Microsoft.EntityFrameworkCore;

namespace Login_DbContext.LoginDbContext;

public partial class Login_Manager : DbContext
{
    public Login_Manager()
    {
    }

    public Login_Manager(DbContextOptions<Login_Manager> options)
        : base(options)
    {
    }

    public virtual DbSet<Frontend> Frontends { get; set; }

    public virtual DbSet<Kitchen> Kitchens { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=localhost;Initial Catalog=LOGIN_MANAGER;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Frontend>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK_Table");
        });

        modelBuilder.Entity<Kitchen>(entity =>
        {
            entity.HasKey(e => e.UserName).HasName("PK__kitchen__7628B51D2FDAF8B5");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}