// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Reservation__DbContext.Models;

public partial class Reservation_Context : DbContext
{
    public Reservation_Context()
    {
    }

    public Reservation_Context(DbContextOptions<Reservation_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Reservation> Reservations { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=localhost;Initial Catalog=FRONTEND_RESERVATION;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Reservation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC070939E04D");

            entity.Property(e => e.CardCvc).IsFixedLength();
            entity.Property(e => e.CardType).IsFixedLength();
            entity.Property(e => e.PaymentType).IsFixedLength();
            entity.Property(e => e.RoomFloor).IsFixedLength();
            entity.Property(e => e.RoomNumber).IsFixedLength();
            entity.Property(e => e.RoomType).IsFixedLength();
            entity.Property(e => e.ZipCode).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}